[package]
name = "watcher"
version = "0.1.0"
authors = ["TENX-S <coldswind@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
chrono = "0.4.19"
anyhow = "1.0.36"
dirs = "3.0.1"
